### PR TITLE
Update version of ITKMontage module

### PR DESCRIPTION
**Pull request by dzenanz**
This includes the correct handling of spacing, exposing tile position tolerance, addition of global optimization with outlier detection and removal.

### CODE REVIEW

**Comment by imikejackson** [comment]
Do we need to go back to the "master" branch to get the updates or are we continuing on with this specific hash?

**Comment by dzenanz** [comment]
Oh, you are right. I forgot that we said we would just do master. Will you update it or do you want me to do it?

**Comment by imikejackson** [comment]
I can put the change to use "master" branch from the Montage Repo.

**Comment by dzenanz** [comment]
I think if there is no `REMOTE_GIT_TAG_Montage` CMake variable, then whatever is written in [Montage.remote.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Remote/Montage.remote.cmake#L5) gets used. I hope it will work if you set `REMOTE_GIT_TAG_Montage` to `master`.

**Pull request closed without merging**
