### PR TITLE
Add ITKMontage as an external project

### PR DESCRIPTION
**Pull request by fbudin69500**
ITKMontage is used by the plugin `MultiscaleFusion`. It is not yet available
as a remote module inside ITK, and therefore has to be built separately.
An option, by default ON, is added, to enable or disable this external project.

### CODE REVIEW

**Review by thewtex — APPROVED** [review]

**Comment by imikejackson** [comment]
Is the ITKMontage basically production ready? If not I would rather have this defaulted to OFF.

**Comment by thewtex** [comment]
+1 for defaulting to OFF.

**Comment by fbudin69500** [comment]
@imikejackson and @thewtex I have updated the patch.

**Review by thewtex — APPROVED** [review]

**Comment by fbudin69500** [comment]
@imikejackson This PR adds ITKMontage that is necessary for the plugin [MultiScaleFusion](https://github.com/BlueQuartzSoftware), and updates ITK to ITKv5 which is required for ITKMontage.

**Comment by imikejackson** [comment]
Currently for production needs we use ITK 4.13.x and I would like to keep it that way until ITK 5.0.0 is fully released. Can we get an option to switch up between ITK 4.13 and 5.0 and IF the developer selects ITK 5.0 then we also include the ITKMontage module?

For those new developers that are standing up systems I would rather not have them installing an alpha quality library ITK but instead stay with the currently used production libraries.

Let me know your thoughts.

**Review by thewtex — APPROVED** [review]
LGTM

**Comment by fbudin69500** [comment]
@imikejackson I added to option to select the version of ITK.

**Comment by fbudin69500** [comment]
@imikejackson ping

**Comment by imikejackson** [comment]
This work has been completed as we now allow the user to select which version of ITK they want to compile against.

**Pull request closed without merging**
