### PR TITLE
Adding TotalVariation ITK remote module

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
If I don't turn `SIMPL_BUILD_TESTING` off, I get many Eigen-related errors of the form:
```text
C:\Misc\BlueQuartz\SIMPL\Source\SIMPLib/Geometry/DerivativeHelpers.h(40): fatal error C1083: Cannot open include file: 'Eigen/Core': No such file or directory (compiling source file C:\Misc\BlueQuartz\SIMPL\Source\SIMPLib\Geometry\EdgeGeom.cpp)
C:\Misc\BlueQuartz\SIMPL\Source\SIMPLib\CoreFilters\util\DivisionOperator.cpp(38): fatal error C1083: Cannot open include file: 'Eigen/Core': No such file or directory
```

**Comment by imikejackson** [comment]
Interesting issue. I am not finding any compile issues with the testing enabled on our side. We were finding issues with VS2019 and ITK5 so we are not testing that particular combination.

**Comment by dzenanz** [comment]
Oh, yes, I have ITK 5 enabled. But this happens with both VS2017 and VS2019.

**Comment by dzenanz** [comment]
This should be merged before https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/182.

**Comment by imikejackson** [comment]
Already Merged.

**Pull request closed without merging**
