### PR TITLE
Missing mkdocs is no longer fatal

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
@imikejackson please review/merge.

**Comment by imikejackson** [comment]
Let's break this into two different PRs. One for the ITKMontage tag and one for the mkdocs changes. I would like to see some more error checking for the mkdocs as it *is* required if the documentation is built so a better warning for the developer would suffice in that instance.

**Comment by dzenanz** [comment]
OK, I created #15 and moved the second commit there.

**Review by imikejackson — COMMENTED** [review]
Can you please make the Warning message as follows:

Mkdocs is missing or not defined and will impact your ability to generate the documentation. When building DREAM3D set SIMPL_USE_MKDOCS = OFF, SIMPL_USE_DISCOUNT = ON or disable the generation of the documentation by the SIMPLView_BUILD_DOCUMENTATION=OFF.

**Comment by dzenanz** [comment]
I updated the warning message and rebased the commit.

**Review by imikejackson — APPROVED** [review]
Looks good.

**Comment by imikejackson** [comment]
You need to sign the commit using "git commit -s"

**Comment by imikejackson** [comment]
Although I am not sure if you can still sign it? You would have to amend the commit and change the commit message to include a signing line.

**Comment by dzenanz** [comment]
I can't sign the commit on either Windows or Linux, I don't have GPG set up. Here are messages on Ubuntu:
```text
dzenan@corista:~/BlueQuartz/DREAM3DSuperbuild$ git commit -a -S --amend
gpg: keyring `/home/dzenan/.gnupg/secring.gpg' created
gpg: keyring `/home/dzenan/.gnupg/pubring.gpg' created
gpg: skipped "Dzenan Zukic <dzenan.zukic@kitware.com>": secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
fatal: failed to write commit object
```
So I only ended up rebasing this commit.

**Comment by dzenanz** [comment]
I guess I will set it up on my primary computer.

**Comment by imikejackson** [comment]
try with a -s instead of -S.

**Comment by dzenanz** [comment]
That did not work. I will set up signing on my computer.

**Comment by dzenanz** [comment]
OK, I signed the commit now. Please merge.

**Pull request merged**
